name: Tag Release

on:
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract version from CHANGELOG.md
        id: changelog
        run: |
          VERSION=$(grep -m1 -Po '(?<=## \[)[0-9]+\.[0-9]+\.[0-9]+' CHANGELOG.md)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create tag if not exists
        run: |
          if git rev-parse "v$VERSION" >/dev/null 2>&1; then
            echo "Tag v$VERSION already exists"
          else
            git config user.name github-actions
            git config user.email github-actions@github.com
            git tag v$VERSION
            git push origin v$VERSION
          fi